---

version: '3.7'

services:
  # Deployed environment
  wtt01:
    build:
      args:
        CHECK_LICENSE: ${CHECK_LICENSE:-0}
        WTT_01_LICENSE_SERVER_URL: ${WTT_01_LICENSE_SERVER_URL:-https://api.wheretrue.com}
        PLATFORM: ${PLATFORM:-x86_64}
        DUCKDB_PLATFORM: ${DUCKDB_PLATFORM:-linux_amd64}
    image: ${DOCKER_IMAGE:-wtt-01-release-with-deb-info}
    environment:
      WTT_01_LICENSE: eae364eb-674e-409d-88a2-53f2a051fafa
      DATA_DIR: /data
    volumes:
      - ./test/sql/wtt-01-release-with-deb-info:/data
    ports:
      - 8080:8080
  wtt01_python:
    environment:
      WTT_01_LICENSE: eae364eb-674e-409d-88a2-53f2a051fafa
      DATA_DIR: /data
    build:
      dockerfile: ./Dockerfile.python
    volumes:
      - ./test/sql/wtt-01-release-with-deb-info:/data
      - ./bin/demo.py:/tmp/demo.py
  # Build environment for manylinux, gcc4
  wtt01_manylinux:
    build:
      dockerfile: ./Dockerfile.manylinux2014
  # Build environment for ubuntu 16.04
  wtt01_ubuntu16:
    build:
      dockerfile: ./Dockerfile.ubuntu1604

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql
