name: Build Python Wheel
description: Build a Wheel image and push it to S3

inputs:
  environment:
    required: true
    description: The environment to deploy to
  aws_account_id:
    required: true
    description: The AWS account ID to deploy to

runs:
  using: "composite"

  steps:
    - name: Install System Deps
      shell: bash
      run: |
        sudo apt-get update -y -qq
        sudo apt-get -y install build-essential  unzip wget libssl-dev

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Python Deps
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install hatch awscli

    - name: Build wheels
      shell: bash
      run: |
        echo "ENVIRONMENT = \"${{ inputs.environment }}\"" > wtt01/_env.py
        hatch build
      working-directory: ./wtt01_python/

    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: wtt01_python
        path: ./wtt01_python/dist

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-deploy-role

    - name: Upload wheels to S3
      shell: bash
      run: aws s3 cp wtt01_python/dist/*.whl s3://wtt-01-dist-${{ inputs.environment }}/python/wheels/
