name: Build Docker Dev Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*dev*"

permissions:
  contents: read
  id-token: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: ["linux_amd64", "linux_arm64"]
        include:
          - arch: "linux_amd64"
            container: "ubuntu:18.04"
            platform: "x86_64"
          - arch: "linux_arm64"
            container: "ubuntu:18.04"
            platform: "aarch64"
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        uses: ./.github/actions/build_docker_image
        with:
          environment: "dev"
          platform: ${{ matrix.platform }}
          check_license: "0"
          aws_account_id: "900163113876"
          repository: "wtt01-dev"
          wtt_01_license_server_url: "https://api.wheretrue.net"
          docker_image: 900163113876.dkr.ecr.us-west-2.amazonaws.com/wtt01-dev
