name: MacOS
on: [workflow_dispatch]
# on: [push, pull_request, repository_dispatch]
# on:
#   push:
#     tags:
#       - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  macos:
    name: MacOS Release (Universal)
    runs-on: macos-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: ["v0.7.0"]

    env:
      OSX_BUILD_UNIVERSAL: 0
      GEN: ninja

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Install Ninja
        run: brew install ninja

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>'}}
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

        # Build extension
      - name: Build extension
        shell: bash
        run: |
          make release
          make test

      - name: Upload extension
        uses: actions/upload-artifact@v2
        with:
          name: duckdb-extension
          path: build/release/extension/wtt01/wtt01.duckdb_extension
