name: MacOS
on:
  pull_request:
    paths-ignore:
    - '**/README.md'
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  macos:
    name: MacOS Release (${{ matrix.osx_build_arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: ['v0.9.1']
        vcpkg_version: ['2023.04.15']
        vcpkg_triplet: ['x64-osx', 'arm64-osx']
        include:
        - vcpkg_triplet: 'x64-osx'
          osx_build_arch: 'x86_64'
          duckdb_arch: 'osx_amd64'
        - vcpkg_triplet: 'arm64-osx'
          osx_build_arch: 'arm64'
          duckdb_arch: 'osx_arm64'

    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}
      OSX_BUILD_ARCH: ${{ matrix.osx_build_arch }}
      GEN: Ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup Ninja
      run: brew install ninja

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ matrix.osx_build_arch }}-${{ github.job }}

    - name: Checkout DuckDB to version
      if: ${{ matrix.duckdb_version != '<submodule_version>'}}
      run: |
        cd duckdb
        git checkout ${{ matrix.duckdb_version }}

    # Build extension
    - name: Build extension
      shell: bash
      run: |
        make release

    # Test extension (only on x86_64)
    - name: Test Extension
      if: ${{ matrix.osx_build_arch == 'x86_64'}}
      shell: bash
      run: |
        make test
