name: Prd Python

on:
  push:
    tags-ignore:
      - "v*dev*"

permissions:
  contents: read
  id-token: write

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build python wheel image
        uses: ./.github/actions/build_python_whl
        with:
          environment: "prd"
          aws_account_id: "894819748579"
