#
# NOTE: if python tests are unused, deleting this file or disabling the workflow on GitHub will speed up CI
#

name: Python
# on: [push, pull_request, repository_dispatch]
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest

    steps:
      - name: Install System Deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -y install build-essential  unzip wget libssl-dev

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "true"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python Deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install hatch

      - name: Build Package
        working-directory: ./wtt01_python
        run: hatch build

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: wtt01_python
          path: ./wtt01_python/dist
