name: Test Python Installs

on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wtt01
      - name: wtt01 smoke Test
        env:
          WTT_01_LICENSE: ${{ secrets.WTT_01_LICENSE }}
        shell: python
        run: |
          import wtt01
          con = wtt01.get_connection()
          con.execute("SELECT gc_content('ATCG') as value;");
          res = con.fetchall()
          assert res[0][0] == .5
