name: Test R Installs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r: [4.2.2]
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: "GitHub Action"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wtt01
      - name: make test.R
        shell: bash
        run: |
          echo "url <- \"https://wtt01.wheretrue.com/R/wtt01r_latest.tar.gz\"" > test.R

          echo "install.packages(\"duckdb\")" >> test.R
          echo "install.packages(url, repos = NULL, type = \"source\")" >> test.R

          echo "library(wtt01r)" >> test.R
          echo "library(DBI)" >> test.R

          echo "con <- wtt01r::get_connection()" >> test.R

          echo "df <- DBI::dbGetQuery(con, \"SELECT gc_content('ATCG') AS gc\")" >> test.R
          echo "print(df)" >> test.R

          cat test.R
      - name: R smoke Test
        shell: bash
        run: |
          R -f test.R
