name: Windows

# on: [push, pull_request, repository_dispatch]
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  windows:
    name: Release
    runs-on: windows-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: ["v0.7.1"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Install OpenSSL
        shell: bash
        run: |
          choco install openssl -y --force

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Checkout DuckDB to version
        # Add commits/tags to build against other DuckDB versions
        if: ${{ matrix.duckdb_version != '<submodule_version>'}}
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - name: Build extension
        run: |
          make release
          build/release/test/Release/unittest.exe

      - uses: actions/upload-artifact@v2
        with:
          name: linux-extensions-64-aarch64
          path: |
            build/release/extension/wtt01/wtt01.duckdb_extension